name: ForcePack
version: "${version}"
main: com.convallyria.forcepack.paper.ForcePackPaper
description: "Paper/Sponge/Velocity plugin to aid resource pack deployment and enforcement, among other utilities."
authors: ["SamB440"]
website: https://fortitude.islandearth.net
api-version: '1.13'
dependencies:
  server:
    ViaVersion:
      load: AFTER
      required: false
    ViaBackwards:
      load: AFTER
      required: false
    ViaRewind:
      load: AFTER
      required: false
    ProtocolLib:
      load: AFTER
      required: false
    Geyser-Spigot:
      load: AFTER
      required: false
    ItemsAdder:
      load: AFTER
      required: false